services:
  postgres:
    image: postgres:15
    container_name: soclose-db
    restart: always
    environment:
      POSTGRES_USER: soclose_user
      POSTGRES_PASSWORD: soclose_pass
      POSTGRES_DB: soclose
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: