name: Déploiement So-Close

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: sigl-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Afficher l’heure du build
        run: date