name: Déploiement So-Close

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: sigl-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Afficher l’heure du build
        run: date
      - name: Vérification Markdown
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: "**/*.md"
      - name: Copier fichier via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: index.html
          target: /home/sigl
