name: Déploiement So-Close
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: sigl-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copier fichier via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "index.html,image.jpg"
          target: ../../data/www
